version: '3.9'

services:
  # ---------------------------
  # PostgreSQL Database
  # ---------------------------
  sonarqube-db:
    image: postgres:latest
    container_name: postgres-sonarqube
    ports:
      - "5432:5432"              # Host port -> Container port
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    networks:
      - sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

  # ---------------------------
  # SonarQube
  # ---------------------------
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"              # Host port -> Container port
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres-sonarqube:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    networks:
      - sonar
    depends_on:
      - sonarqube-db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

# ---------------------------
# Volumes for persistent storage
# ---------------------------
volumes:
  sonarqube_db:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

# ---------------------------
# Network
# ---------------------------
networks:
  sonar:
    driver: bridge
    name: sonar
    external: true
